/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projekpbo;

/**
 *
 * @author galan
 */
public class FormMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormMenu.class.getName());

    /**
     * Creates new form FormMenu
     */
    public FormMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuDivisi = new javax.swing.JMenu();
        btnMenuDivisi = new javax.swing.JMenu();
        btnMenuDivisiClose = new javax.swing.JMenu();
        MenuJabatan = new javax.swing.JMenu();
        btnMenuJabatan = new javax.swing.JMenu();
        btnMenuJabatanClose = new javax.swing.JMenu();
        MenuPegawai = new javax.swing.JMenu();
        btnFormPegawai = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Copyright @2026");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(jLabel1)
                .addContainerGap(240, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(378, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 550, 420));

        MenuDivisi.setText("== Divisi ==");
        MenuDivisi.addActionListener(this::MenuDivisiActionPerformed);

        btnMenuDivisi.setText("Form Divisi");
        btnMenuDivisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuDivisiMouseClicked(evt);
            }
        });
        btnMenuDivisi.addActionListener(this::btnMenuDivisiActionPerformed);
        MenuDivisi.add(btnMenuDivisi);

        btnMenuDivisiClose.setText("Close");
        btnMenuDivisiClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuDivisiCloseMouseClicked(evt);
            }
        });
        btnMenuDivisiClose.addActionListener(this::btnMenuDivisiCloseActionPerformed);
        MenuDivisi.add(btnMenuDivisiClose);

        jMenuBar1.add(MenuDivisi);

        MenuJabatan.setText("== Jabatan ==");

        btnMenuJabatan.setText("Form Jabatan");
        btnMenuJabatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuJabatanMouseClicked(evt);
            }
        });
        MenuJabatan.add(btnMenuJabatan);

        btnMenuJabatanClose.setText("Close");
        btnMenuJabatanClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuJabatanCloseMouseClicked(evt);
            }
        });
        MenuJabatan.add(btnMenuJabatanClose);

        jMenuBar1.add(MenuJabatan);

        MenuPegawai.setText("== Pegawai ==");

        btnFormPegawai.setText("Form Pegawai");
        MenuPegawai.add(btnFormPegawai);

        jMenu1.setText("Close");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        MenuPegawai.add(jMenu1);

        jMenuBar1.add(MenuPegawai);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuDivisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDivisiActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_MenuDivisiActionPerformed

    private void btnMenuDivisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuDivisiActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnMenuDivisiActionPerformed

    private void btnMenuDivisiCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuDivisiCloseActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnMenuDivisiCloseActionPerformed

    private void btnMenuDivisiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuDivisiMouseClicked
        // TODO add your handling code here:
        FormDivisi formDivisi = new FormDivisi();
        formDivisi.setVisible(true);
    }//GEN-LAST:event_btnMenuDivisiMouseClicked

    private void btnMenuDivisiCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuDivisiCloseMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnMenuDivisiCloseMouseClicked

    private void btnMenuJabatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuJabatanMouseClicked
        // TODO add your handling code here:
        FormJabatan formJabatan = new FormJabatan();
        formJabatan.setVisible(true);
    }//GEN-LAST:event_btnMenuJabatanMouseClicked

    private void btnMenuJabatanCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuJabatanCloseMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnMenuJabatanCloseMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuDivisi;
    private javax.swing.JMenu MenuJabatan;
    private javax.swing.JMenu MenuPegawai;
    private javax.swing.JMenu btnFormPegawai;
    private javax.swing.JMenu btnMenuDivisi;
    private javax.swing.JMenu btnMenuDivisiClose;
    private javax.swing.JMenu btnMenuJabatan;
    private javax.swing.JMenu btnMenuJabatanClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
